services:
  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - redis
    env_file: .env
    environment:
      PIPENV_VENV_IN_PROJECT: "1"
    volumes:
      - .:/app
    command: python -m app.main
